import type { Metadata } from "next"
import { Noto_Sans } from "next/font/google"
import "./globals.css"
import NavBar from "./components/navbar"
import clsx from "clsx"
import dynamic from "next/dynamic"

const notoSans = Noto_Sans({ subsets: ["latin"] })

const NoSSR = dynamic(() => import("./components/navbar"), { ssr: false })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx(
          notoSans.className,
          "flex min-h-screen flex-col bg-[#dcccbc] 2xl:flex-row"
        )}
      >
        <NoSSR />
        {children}
      </body>
    </html>
  )
}
