import type { Metadata } from "next"
import { Noto_Sans } from "next/font/google"
import "./globals.css"
import NavBar from "./components/navbar"

const notoSans = Noto_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <div className="flex min-h-screen flex-col bg-[#dcccbc] lg:flex-row">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  )
}
